Traceback (most recent call last):
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/hyhu/anaconda3/envs/quantum/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
stabilizer.stabilizer_state('XXY','-YYI','IZZ')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [21][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mstabilizer[49m[38;5;241;43m.[39;49m[43mstabilizer_state[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mXXY[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43m-YYI[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mIZZ[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/Dropbox/Projects/Harvard/PyCliffordBook/PyBook/src/stabilizer.py:278[0m, in [0;36mstabilizer_state[0;34m(*stabilizers)[0m
[1;32m    276[0m [38;5;66;03m# validity check:[39;00m
[1;32m    277[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m (acq_mat(stabilizers[38;5;241m.[39mgs) [38;5;241m==[39m [38;5;241m0[39m)[38;5;241m.[39mall():
[0;32m--> 278[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124mstabilizers must all commute with each other.[39m[38;5;124m'[39m)
[1;32m    279[0m state [38;5;241m=[39m maximally_mixed_state(stabilizers[38;5;241m.[39mN)
[1;32m    280[0m state[38;5;241m.[39mgs, state[38;5;241m.[39mr [38;5;241m=[39m stabilizer_project(state[38;5;241m.[39mgs, numpy[38;5;241m.[39mflipud(stabilizers[38;5;241m.[39mgs), state[38;5;241m.[39mr)

[0;31mValueError[0m: stabilizers must all commute with each other.
ValueError: stabilizers must all commute with each other.

